language: node_js
node_js:
  - "12"
  - "14"
  - "16"
script: "npm test"
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          branch: master
